=== DariaAdelinne/ades-soft-stitches-site/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume,prenume,varsta,adresa,email,telefon,studii)>
<!ATTLIST persoana id NMTOKEN #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT studii (liceu,universitate,facultate)>
<!ELEMENT liceu (#PCDATA)>
<!ELEMENT universitate (#PCDATA)>
<!ELEMENT facultate (#PCDATA)>

=== DariaAdelinne/ades-soft-stitches-site/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>Bld.Nicolae Iorga</strada>
            <numar>30</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <email>ion.popescu@gmail.com</email>
        <telefon>0712345678</telefon>
        <studii>
            <liceu>Liceul Regina Maria Dorohoi</liceu>
            <universitate>Universitatea Gheorghe Asachi Iasi</universitate>
            <facultate>Facultatea de Automatica si Calculatoare</facultate>
        </studii>
    </persoana>

    <persoana id="2">
        <nume>Ionel</nume>
        <prenume>Maria</prenume>
        <varsta>24</varsta>
        <adresa>
            <strada>Bld.Florilor</strada>
            <numar>31</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <email>ionelMaria@gmail.com</email>
        <telefon>0711111111</telefon>
        <studii>
            <liceu>Liceul Regina Maria Constanta</liceu>
            <universitate>Universitatea Gheorghe Asachi Iasi</universitate>
            <facultate>Facultatea de Design</facultate>
        </studii>
    </persoana>

    <persoana id="3">
        <nume>Ghiorghiu</nume>
        <prenume>Teodora</prenume>
        <varsta>22</varsta>
        <adresa>
            <strada>Bld.1 Mai</strada>
            <numar>14</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <email>ghiorghiuteodora@gmail.com</email>
        <telefon>0722222222</telefon>
        <studii>
            <liceu>Colegiul Grigore Ghica</liceu>
            <universitate>Universitatea Alexandru Ioan Cuza Iasi</universitate>
            <facultate>Facultatea de Psihologie</facultate>
        </studii>
    </persoana>
</persoane>
